### ISSUE TITLE
Wrong inclusion of node_modules files

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-agent-js#127]

**Comment by lachrist** [comment]
This was not a bug. The agent was complaining that source map files were missing in `node_modules` because filtering is applied on source files. So it always attempt to fetch source map files even if the file is in `node_modules`. If the source map file is missing, the input file is considered to be the source file so there is no problem. I downgrade the log message to debug to be less noisy in: 6aa5da98782b7768849d39afa3d47be0cc3f3b73
